### ISSUE TITLE
Unable to see the Older transactions on TF Connect app

### ISSUE THREAD

**Issue by mahendravarmayadala93** [threefoldtech/threefold_connect#613]
RobertL and a user named K on Telegram noted that they could view only the recent transactions from today (10th July 2024) and not the older ones.

Shang and I verified on the TF Connect app; we can access the previous transactions since we did not farm, and our transaction count is lower until now.

**Comment by ramezsaeed** [comment]
lets try to compare same wallet on TF connect and stellar and make sure they are the same transactions

**Comment by zaelgohary** [comment]
@mahendravarmayadala93 Could you please share the Stellar address that encountered the issue?

**Comment by mahendravarmayadala93** [comment]
Hey @zaelgohary !Robert didn't mention the specific wallet address in his when he reported on Telegram However, according to our previous Live chat conversations, his wallet address is: [GBWDMJFWJQIQNWB3QFGSRZPEGLPFJIH7E4PYACT52NKL43Z6DHCNUPW7](https://stellar.expert/explorer/public/account/GBWDMJFWJQIQNWB3QFGSRZPEGLPFJIH7E4PYACT52NKL43Z6DHCNUPW7).

**Comment by zaelgohary** [comment]
WIP:

The issue is related to pagination. Currently working on implementing pagination in the transactions page.

**Comment by zaelgohary** [comment]
Work Completed:

- Fixed walletAssets err
- Edited getTransactions to include limit & offset
- Added infinite scroll pagination

**Comment by khaledyoussef24** [comment]
made a multiple transactions but 
still not working with me on tfchain transactions
is there any thing am missing ?

![Image](https://github.com/user-attachments/assets/272631d2-aa55-45ab-8b57-48dda78ba7a7)

**Comment by khaledyoussef24** [comment]
should this works on tfchain and stellar or stellar only ?
it works with stellar

**Comment by AhmedHanafy725** [comment]
> should this works on tfchain and stellar or stellar only ?

stellar only

**Comment by khaledyoussef24** [comment]
verified and working fine on ios version 18
version 4.0.1 - 185
Stellar transfers are working fine 

![Image](https://github.com/user-attachments/assets/855cb85f-8ff5-4b8e-b221-4d749139bd97)
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407473#case_4046922)

**Comment by ramezsaeed** [comment]
@khaledyoussef24 
I think u need to test pagination too

**Comment by atefnazmy** [comment]
- Verified on Android 14,
- Threefold-Connect: 4.0.3 - 185
- APK: 04-02-2025
- The App displays the most recent transactions on the first page, and when scrolling down, older transactions loaded and displayed correctly.
#### Screen shot

https://github.com/user-attachments/assets/91a224b2-815e-416c-becc-0b0dbcbb4443

#### Related Link:
- [Testcase Link](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407473#case_4046922)
